version: '3.7'

services:
  shard_server_0:
    image: mongo:4.0.19
    container_name: shard_server_0
    networks:
          mongo_network:
              ipv4_address: 172.20.0.11
    ports:
      - 27018:27018
      - 30001:30001
    volumes:
      - ./data/shard_server_0/data/se0:/data/db
      - ./data/shard_server_0/data/se1:/data/set1
      - ./data/shard_server_0/data/configdb:/data/configdb
      - ./data/shard_server_0/data/backup:/data/backup
    command: --shardsvr --replSet=shard_server0 --bind_ip_all
    depends_on:
      - rs_config_server_0
      - rs_config_server_1

  shard_server_1:
    image: mongo:4.0.19
    container_name: shard_server_1
    networks:
          mongo_network:
              ipv4_address: 172.20.0.12
    ports:
      - 27028:27018
      - 30002:30002
    volumes:
      - ./data/shard_server_1/data/se0:/data/db
      - ./data/shard_server_1/data/se1:/data/set1
      - ./data/shard_server_1/data/configdb:/data/configdb
      - ./data/shard_server_1/data/backup:/data/backup
    command: --shardsvr --replSet=shard_server0 --bind_ip_all
    depends_on:
      - rs_config_server_0
      - rs_config_server_1

  shard_server_2:
    image: mongo:4.0.19
    container_name: shard_server_2
    networks:
          mongo_network:
              ipv4_address: 172.20.0.16
    ports:
      - 27038:27018
      - 30003:30003
    volumes:
      - ./data/shard_server_2/data/se0:/data/db
      - ./data/shard_server_2/data/se1:/data/set1
      - ./data/shard_server_2/data/configdb:/data/configdb
      - ./data/shard_server_2/data/backup:/data/backup
    command: --shardsvr --replSet=shard_server0 --bind_ip_all
    depends_on:
      - rs_config_server_0
      - rs_config_server_1

  rs_config_server_0:
      container_name: rs_config_server_0
      networks:
          mongo_network:
              ipv4_address: 172.20.0.13
      image: mongo:4.0.19
      volumes:
          - ./data/rs_config_server_0/data/db:/data/db
          - ./data/rs_config_server_0/data/configdb:/data/configdb
      ports:
          - 27030:27019
      command: --configsvr --replSet "rs_config_server" --bind_ip_all
      restart: always

  rs_config_server_1:
      container_name: rs_config_server_1
      networks:
          mongo_network:
              ipv4_address: 172.20.0.14
      image: mongo:4.0.19
      volumes:
          - ./data/rs_config_server_1/data/db:/data/db
          - ./data/rs_config_server_1/data/configdb:/data/configdb
      ports:
          - 27031:27019
      command: --configsvr --replSet "rs_config_server" --bind_ip_all
      restart: always

  mongos:
      container_name: mongos
      networks:
          mongo_network:
              ipv4_address: 172.20.0.15
      image: mongo:4.0.19
      ports:
          - 27017:27017
      volumes:
          - ./data/mongos/data/db:/data/db
          - ./data/mongos/data/configdb:/data/configdb
      entrypoint: mongos
      command: --configdb rs_config_server/172.20.0.13:27019,172.20.0.14:27019 --bind_ip_all
      depends_on:
          - shard_server_0
          - shard_server_1
          - shard_server_2
networks:
    mongo_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.10/24