version: '3'

services:
  flask:
    build: ./flask
    volumes:
      - ./app:/app
      - ./flask/uwsgi.ini:/etc/uwsgi/uwsgi.ini
  nginx:
    image: nginx:1.12.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
      - ./app:/usr/share/nginx/app
    depends_on:
      - flask