version: '3'

services:
  php56:
    container_name: lamp_php56
    build: ./php56
    ports:
      - "9000:9000"
    volumes:
      - ./php56/www.conf:/usr/local/etc/php.d/www.conf
      - ./php56/local.env:/usr/local/etc/php.d/local.env
      - ./php56/php.ini:/usr/local/etc/php/php.ini
      - ./php56/logs:/var/log/
      - ./app:/usr/share/nginx/app
    env_file:
      - ./local.env
    depends_on:
      - mysql

  nginx:
    container_name: lamp_nginx
    image: nginx:1.12.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
      - ./app:/usr/share/nginx/app
    env_file:
      - ./local.env
    depends_on:
      - php56

  mysql:
    container_name: lamp_mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/datadir:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d/
    env_file:
      - ./local.env