<?php

namespace App\Component\room\src\constants;

class RspStructConstant
{
    const LIST = [
        'data'         => [
            'il_id'              => 'int',
            'room_id'            => 'string',
            'subject'            => 'string',
            'account_id'         => 'int',
            'inav_id'            => 'int',
            'channel_id'         => 'string',
            'nify_channel'       => 'int',
            'record_id'          => '',
            'start_time'         => 'datetime',
            'begin_time_stamp'   => 'int',
            'introduction'       => 'string',
            'category'           => 'int',
            'cover_image'        => 'string',
            'topics'             => 'string',
            'layout'             => 'int',
            'status'             => 'int',
            'is_delete'          => 'int',
            'message_approval'   => 'int',
            'created_at'         => 'datetime',
            'updated_at'         => 'datetime',
            'app_id'             => 'string',
            'like'               => '0',
            'live_type'          => 'int',
            'warm_type'          => 'int',
            'teacher_name'       => 'string',
            'is_open_document'   => 'int',
            'live_mode'          => 'int',
            'message_total'      => 'int',
            'mode'               => 'int',
            'limit_type'         => 'int',
            'extend'             => 'string',
            'live_time'          => 'string',
            'name'               => 'string',
            'desc'               => 'string',
            'image'              => 'string',
            'view_url'           => 'string',
            'watch_url'          => 'string',
            'status_str'         => 'string',
            'live_room_type_str' => 'string',
            'begin_time'         => 'datetime',
            'dept'               => 'string',
            'org'                => 'string',
            'dept_name'          => 'string',
            'org_name'           => 'string',
            'account_name'       => 'string',
            'role_name'       => 'string',
        ]
    ];

    const INVITED_LIST = [
        'data'         => [
            'il_id'              => 'int',
            'room_id'            => 'string',
            'subject'            => 'string',
            'account_id'         => 'int',
            'inav_id'            => 'int',
            'channel_id'         => 'string',
            'nify_channel'       => 'int',
            'record_id'          => '',
            'start_time'         => 'datetime',
            'begin_time_stamp'   => 'int',
            'introduction'       => 'string',
            'category'           => 'int',
            'cover_image'        => 'string',
            'topics'             => 'string',
            'layout'             => 'int',
            'status'             => 'int',
            'status_str'         => 'string',
            'is_delete'          => 'int',
            'message_approval'   => 'int',
            'created_at'         => 'datetime',
            'updated_at'         => 'datetime',
            'app_id'             => 'string',
            'like'               => '0',
            'live_type'          => 'int',
            'warm_type'          => 'int',
            'teacher_name'       => 'string',
            'is_open_document'   => 'int',
            'live_mode'          => 'int',
            'message_total'      => 'int',
            'mode'               => 'int',
            'limit_type'         => 'int',
            'extend'             => 'string',
            'role_name'          => 'string',
            'dept'               => 'string',
            'org'                => 'string',
            'dept_name'          => 'string',
            'org_name'           => 'string',
            'account_name'       => 'string',
        ]
    ];
}
