version: "3"
services:
  nginx_master:
    build: ./nginx
    volumes:
      - ./html/index-master.html:/usr/share/nginx/html/index.html
      - ./keepalived/master.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.20.0.11
    cap_add: 
      - ALL
  nginx_slave:
    build: ./nginx
    volumes:
      - ./html/index-slave.html:/usr/share/nginx/html/index.html
      - ./keepalived/slave.conf:/etc/keepalived/keepalived.conf
    networks:
      static-network:
        ipv4_address: 172.20.0.12
    cap_add: 
        - ALL
  proxy:
    image: haproxy:1.7-alpine
    ports:
      - 6301:6301
      - 8080:8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - static-network

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24