apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: lnmp-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 30001
  selector:
    app: lnmp-mysql
  clusterIP: 10.96.0.12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: lnmp-mysql
spec:
  selector:
    matchLabels:
      app: lnmp-mysql
  template:
    metadata:
      labels:
        app: lnmp-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: local-volume-claim
